using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApp.Models
{
    /// <summary>
    /// BotConfiguration model represents the settings and parameters for a user's bot
    /// This entity maps to the BotConfigurations table in SQL Server with simplified JSON storage
    /// </summary>
    [Table("BotConfigurations")]
    public class BotConfiguration
    {
        /// <summary>
        /// Primary key - automatically generated by database
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("ConfigId")]
        public long ConfigId { get; set; }

        /// <summary>
        /// Foreign key to UserBots table
        /// </summary>
        [Required]
        [Column("UserBotId")]
        public long UserBotId { get; set; }

        /// <summary>
        /// JSON configuration parameters for the bot - flexible storage for all bot types
        /// </summary>
        [Column("Parameters", TypeName = "nvarchar(max)")]
        public string? Parameters { get; set; }
        /// </summary>
        [Required]
        /// <summary>
        /// Navigation property - UserBot this configuration belongs to
        /// </summary>
        [ForeignKey("UserBotId")]
        public virtual UserBot UserBot { get; set; } = null!;
    }
}