using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApp.Models
{
    /// <summary>
    /// TradingBot model represents pre-configured bot templates available to users
    /// This entity maps to the TradingBots table in SQL Server
    /// </summary>
    [Table("TradingBots")]
    public class TradingBot
    {
        /// <summary>
        /// Primary key - automatically generated by database
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("BotId")]
        public long BotId { get; set; }

        /// <summary>
        /// Name of the trading bot template
        /// </summary>
        [Required]
        [StringLength(100)]
        [Column("Name")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Trading strategy type (e.g., "WeeklyDCA", "GridTrading", etc.)
        /// </summary>
        [Required]
        [StringLength(50)]
        [Column("Strategy")]
        public string Strategy { get; set; } = string.Empty;

        /// <summary>
        /// Description of what this bot does
        /// </summary>
        [StringLength(500)]
        [Column("Description")]
        public string? Description { get; set; }

        /// <summary>
        /// When this bot template was created
        /// </summary>
        [Required]
        [Column("Created")]
        public DateTime Created { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Navigation property - User instances of this bot template
        /// </summary>
        public virtual ICollection<UserBot> UserBots { get; set; } = new List<UserBot>();
    }
}