using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApp.Models
{
    /// <summary>
    /// User model to represent a user in the database.
    /// This entity will be mapped to the Users table in SQL Server.
    /// </summary>
    [Table("Users")]
    public class User
    {
        /// <summary>
        /// Primary key - automatically generated by database
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }
        
        /// <summary>
        /// User's email address - must be unique across all users
        /// </summary>
        [Required]
        [EmailAddress]
        [StringLength(256)]
        [Column(TypeName = "nvarchar(256)")]
        public string Email { get; set; } = string.Empty;
        
        /// <summary>
        /// Username for login - must be unique across all users
        /// </summary>
        [Required]
        [StringLength(50)]
        [Column(TypeName = "nvarchar(50)")]
        public string Username { get; set; } = string.Empty;
        
        /// <summary>
        /// Hashed password - never store plain text passwords
        /// </summary>
        [Required]
        [StringLength(500)]
        [Column(TypeName = "nvarchar(500)")]
        public string PasswordHash { get; set; } = string.Empty;
        
        /// <summary>
        /// When the user account was created
        /// </summary>
        [Required]
        [Column(TypeName = "datetime2")]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Navigation property for user's portfolios
        /// </summary>
        public virtual ICollection<Portfolio> Portfolios { get; set; } = new List<Portfolio>();
    }
}
